break_into_partial_movies: false
camera_qualities:
  default_quality: four_by_three
  high:
    frame_rate: 30
    resolution: 1920x1080
  low:
    frame_rate: 15
    resolution: 854x480
  medium:
    frame_rate: 30
    resolution: 1280x720
  ultra_high:
    frame_rate: 30
    resolution: 3840x2160

directories:
  mirror_module_path: false
full_screen: false
style:
  background_color: '#212121'
  font: Consolas
tex:
  executable: latex
  intermediate_filetype: dvi
  template_file: tex_template.tex
  text_to_replace: '[tex_expression]'
universal_import_line: from manimlib import *
window_monitor: 0
window_position: UR
